---

- name: Setup Debian specific variables (set_fact)
  set_fact:
    tor_user: debian-tor
    tor_DataDir: /var/lib/tor-instances
    tor_ConfDir: /etc/tor/instances
    tor_RunAsDaemon: 0
  tags:
   - reconfigure
   - renewkey

- name: Ensure torproject gpg key is installed (A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89)
  apt_key:
    data: "{{ lookup('file', 'deb.torproject.org_A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.pub') }}"
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: present

- name: Ensure torproject.org repository is present (APT)
  apt_repository:
    repo: "deb http://deb.torproject.org/torproject.org {{ tor_distribution_release }} main"
    state: present 
    update_cache: yes

# we specifically opt for present over latest to improve performance
# "latest" is covered by auto updates
- name: Ensure Tor is installed (APT)
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: 
    - deb.torproject.org-keyring
    - tor
  # apt starts a tor client instance by default after installing the package
  # we do not need that
  notify:
    - stop-and-mask default tor instance

# Background:
# https://github.com/nusenu/ansible-relayor/issues/72
- name: Ensure systemd generator folder exists (Debian Testing and Ubuntu)
  file:
    path: /etc/systemd/system-generators
    state: directory
    mode: 0755
  when: ansible_lsb.codename != 'jessie'

- name: Ensure custom systemd generator is in place (Debian/Ubuntu only)
  copy:
   src: tor-generator
   dest: "{{ (ansible_lsb.codename == 'jessie')|ternary('/lib/systemd/system-generators/relayor-generator', '/etc/systemd/system-generators/tor-generator') }}"
   owner: root
   mode: 755

- name: Ensure the maintainer's generator is disabled (Debian 8 only)
  command: dpkg-statoverride --update --add root root 644 /lib/systemd/system-generators/tor-generator
  when: ansible_lsb.codename == 'jessie'


#- name: Ensure AppArmor allows access to necessary files (Ubuntu)
#  lineinfile: dest=/etc/apparmor.d/local/system_tor line={{ item }}
#  with_items:
#    - '/etc/tor/enabled/*\ r,'
#    - '/{,var/}run/tor/*.pid\ w,'
#    - '/var/lib/tor/**\ w,'
#  when: ansible_distribution == 'Ubuntu'
#  notify: restart apparmor

- meta: flush_handlers
