---

- name: Ensure Tor starts at boot (FreeBSD)
  lineinfile: dest=/etc/rc.local line="/usr/local/bin/tor -f {{ tor_ConfDir }}/{{ item.name }}.torrc" create=yes
  with_items: "{{ tor_identities }}"

- name: Ensure PidDir exists (FreeBSD)
  file:
    path: "{{ tor_PidDir }}"
    state: directory
    owner: root
    mode: 0755

- name: Ensure PidDir is owned by per-instance tor_user (FreeBSD)
  file:
    path: "{{ tor_PidDir }}/{{ item.name }}"
    state: directory
    owner: "_tor-{{ item.name }}"
    mode: 0700
  with_items: "{{ tor_identities }}"

- name: Ensure Tor instances are reloaded if its torrc changed (FreeBSD)
  shell: "kill -HUP `cat {{ tor_PidDir }}/{{ item.item.name }}/pid`"
  ignore_errors: yes
  with_items: "{{ instances.results }}"
  when: item|changed
  tags:
   - reconfigure

- name: Ensure Tor instances are running (FreeBSD)
  shell: "kill -0 `cat {{ tor_PidDir }}/{{ item.name }}/pid` || tor -f {{ tor_ConfDir }}/{{ item.name }}.torrc"
  with_items: "{{ tor_identities }}"
  tags:
   - reconfigure
