---
# Linux/systemd section (uses service module)
# ===========================================

- name: Ensure Tor instances are reloaded if its torrc changed (Linux/systemd)
  service:
    name: "tor@{{ item.item.name }}.service"
    state: reloaded
  with_items: "{{ instances.results }}"
  when: item|changed
  tags:
   - reconfigure

- name: Ensure Tor instances are enabled and started (Linux/systemd)
  service:
    name: "tor@{{ item.name }}.service"
    enabled: yes
    state: started
  with_items: "{{ tor_identities }}"
