---

- include: ip-list.yml
  tags:
    - always

- include: apt_install.yml
  when: ansible_pkg_mgr == 'apt'
  tags:
   - debian
   - install

- include: rpm_install.yml
  when: ansible_os_family == 'RedHat'
  tags:
   - centos
   - fedora
   - install

- include: openbsd_prepare.yml
  when: ansible_system == 'OpenBSD'
  tags:
   - openbsd

- include: freebsd_prepare.yml
  when: ansible_system == 'FreeBSD'
  tags:
   - freebsd

- name: Ensure tor package is installed (*BSD)
  become: yes
  package:
    name: tor
    state: present
  when: (ansible_system == 'OpenBSD') or (ansible_system == 'FreeBSD')
  tags:
   - openbsd
   - freebsd
   - install

- include: configure.yml
  tags:
   - debian
   - centos
   - fedora
   - openbsd
   - freebsd

- include: linux_service.yml
  when: ansible_system == 'Linux'
  tags:
   - debian
   - centos
   - fedora

- include: openbsd_service.yml
  when: ansible_system == 'OpenBSD'
  tags:
   - openbsd

- include: freebsd_service.yml
  when: ansible_system == 'FreeBSD'
  tags:
   - freebsd
