---

- include: apt_install.yml
  when: ansible_pkg_mgr == 'apt'
  tags:
   - debian
   - install

- include: yum_install.yml
  when: ansible_pkg_mgr == 'yum'
  tags:
   - centos
   - install

- include: openbsd_install.yml
  when: ansible_pkg_mgr == 'openbsd_pkg'
  tags:
   - openbsd
   - install

- include: freebsd_install.yml
  when: ansible_pkg_mgr == 'pkgng'
  tags:
   - freebsd
   - install

- include: dnf_install.yml
  when: ansible_pkg_mgr == 'dnf'
  tags:
   - fedora
   - install

- include: configure.yml
