---
# OpenBSD section (uses service module)
# This is basically a copy from the Linux
# section, but it requires different service
# names and additional arguments.
# =====================================

# OpenBSD does not support multi-instance rc.d
# # so we link as many pseudo rc scripts as we need.
# # OpenBSD does not like dots in rc filenames so
# # we replace them with underscores.
- name: Create links to the service files (OpenBSD)
  become: yes
  file:
    src: /etc/rc.d/tor
    state: link
    path: "/etc/rc.d/tor{{ item.name|replace('.','_') }}"
  with_items: "{{ tor_identities }}"

- name: Ensure Tor instances are enabled and started (OpenBSD)
  become: yes
  service:
   name: "tor{{ item.name|replace('.','_') }}"
   arguments: "-f {{ tor_ConfDir }}/{{ item.name }}.torrc"
   enabled: yes
   state: started
  with_items: "{{ tor_identities }}"

- name: Ensure Tor instances are reloaded if its torrc changed (OpenBSD)
  become: yes
  service:
    name: "tor{{ item.item.name|replace('.','_') }}"
    state: reloaded
  with_items: "{{ instances.results }}"
  when: item|changed
  tags:
   - reconfigure
