---
- name: stop-and-mask default tor instance
  become: yes
  shell: systemctl stop tor@default && systemctl mask tor@default

- name: restart apparmor
  become: yes
  service: name=apparmor state=restarted

- name: systemctl daemon-reload
  become: yes
  command: systemctl daemon-reload

- name: re-gather facts
  setup:
