---
- name: stop-and-mask default tor instance
  become: yes
  shell: systemctl stop tor@default && systemctl mask tor@default
  when: ansible_pkg_mgr == 'apt'

- name: restart apparmor
  become: yes
  service: name=apparmor state=restarted

- name: systemctl daemon-reload
  become: yes
  command: systemctl daemon-reload

- name: re-gather facts
  setup:
  when: ansible_pkg_mgr == 'dnf'
